#!/bin/bash


curl -X POST http://localhost:5000/predict \
-H "Content-Type: application/json" \
-d @- <<  EOF
{
    "text": 
    "Carlyle Looks Toward Commercial Aerospace (Reuters) Reuters - Private
    investment firm Carlyle Group, which has a reputation for making well-timed
    and occasionally controversial plays in the defense industry, has quietly
    placed its bets on another part of the market."
}
EOF
